name: Download stop birokraciji

on:
  push:
    branches:
    - main  # todo: change to periodical

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements-scrap.txt

      - name: Download data
        run: python scripts/stop_birokraciji_scraper.py

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # created by workflow
          publish_dir: ./data/stop-birokraciji
          publish_branch: gh-pages
          destination_dir: stop-birokraciji
