name: Generate index

on:
  push:
    branches:
      - gh-pages

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}  # current branch

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Generate indexes
        run: python _scripts/generate_index.py

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "*/index.html"
          message: Update indexes
          committer_name: GitHub Actions
          committer_email: actions@github.com
